services:
  db_service:
    image: postgres
    container_name: db_service
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_service
    env_file:
      - .env

volumes:
  pg_volume: